### ISSUE TITLE
Hide Add/Remove buttons for array

### ISSUE THREAD

**Issue by joelguittet** [jsonform/jsonform#358]
Hello,

Is there a way to totally disable and hide the Add/Remove buttons for an array ? I want to prevent user to change the number of element when the form is loaded (he has only the permission to change the elements).

Thanks,

Joel

**Comment by tchapi** [comment]
Hi @joelguittet 

A very naive and simple approach would be to hide them with CSS:

```css
._jsonform-array-addmore, ._jsonform-array-deletelast {
    display: none;
}
```

But if your user is tech-savvy and knows how to use devtools, he could find them and re-show them.
