### ISSUE TITLE
anyone know how to move a button?

### ISSUE THREAD

**Issue by sdetweil** [jsonform/jsonform#466]
I have a structured form.. the section is a fieldset
I want a button to the right of the legend in the fieldset

I can move it right , but I really want it up at the end of the word 'config' , but append doesn't work for groups.. (too bad) 
```
    "type": "fieldset",
                  "title": "config",
                  "append":"<button>hi</button>",
                  "items": [
                    {
                      "type": "button",
                      "title": "Open module readme",
                      "htmlClass": "repo_button",
                      "onClick": "(evt,node)=>{let siblings=$(evt.target).siblings('.repo_url');let element=siblings.toArray()[0];let url=element.innerText;window.open(url)}"
                    },
```

![Image](https://github.com/user-attachments/assets/ba15a86d-1edc-4a0d-aa5d-d85ffe9a90ce)

**Comment by sdetweil** [comment]
takes three things
added htmlClass:"moduleName"  // can be anything you like to target that element

```css
fieldset .moduleName {        /* add top padding to the fieldset element (the legend) */
   padding-top: 10px;
}
.moduleName legend {       /* make it display: contents to wrap the next element */
   display: contents;
}
.moduleName legend + button {  /* add a margin-bottom to the immediate element wrapped by display-contents */
   margin-bottom: 15px;
}
```

![Image](https://github.com/user-attachments/assets/8b695940-f507-4fe7-b053-a90c04405474)
